export const types = {

	login: 'Auth Login',
	logout: 'Auth Logout',

	uiLoginShowLoader: 'UI Login show loading',
	uiLoginFinishLoader: 'UI Login finish loading',
	uiLoginShowMessageError: 'UI Login show message error',
	uiLoginRemoveMessageError: 'UI Login remove message error',

	foldersInitLoaded: 'Folders Init Loaded',
	foldersSetChildren: 'Folders Set children',
	foldersSaveIds: 'Folders Save ids',
	foldersRemoveId: 'Folders Remove id',
	foldersSaveAll: 'Folders Save all folders',
	foldersSelected: 'Folders Selected',
	foldersRemoveAll: 'Folders Remove All',

	auditDataLoaded: 'Audit Data Loaded',

	uiAuditShowLoader: 'UI Audit show loading',
	uiAuditFinishLoader: 'UI Audit finish loading',

	searchFieldsLoaded: 'Search Fields loaded',
	searchLoaded: 'Search Loaded',
	searchDocumentDeleted: 'Search Deleted document',
	searchSetText: 'Search Set Text',
	searchRemoveText: 'Search Remove Text',
	searchRemoveAll: 'Search Remove All',
	searchSetValueFilter: 'Search Set value filter',
	searchClearAllFilters: 'Search Clear all filters',
	searchSubscribeDocumentFinish: 'Search subscribe document finish',

	docsDocumentsTypeLoaded: 'Documents Type documents loaded',
	docsDetailDocumentTypeLoaded: 'Documents Detail document type loaded',
	docsRemoveAll: 'Documents Remove all',
	docsRemoveDetailDocumentType: 'Documents Remove detail document type',
	docsSetValueField: 'Documents Set value field',
	docsSaveFormFinish: 'Documents Save form finish',
	docsSaveFolderId: 'Documents Save folder ID',
	docsSaveFileIdLoaded: 'Documents Save file ID loaded',
	docsSaveThumbnailGenerated: 'Documents Save thumbnailGenerated',
	docsSaveThumbnail: 'Documents Save thumbnail',
	docsClear: 'Documents Clear',
	docsCloseModalMultiSelect: 'Documents Close modal multi select',
	docsDocumentByIdLoaded: 'Documents Document by ID loaded',
	docsTagsLoaded: 'Documents Tags Loaded',
	docsSaveVersioningType: 'Documents Save versioning type',
	docsSaveVersioningComments: 'Documents Save versioning comments',
	docsClearVersioningType: 'Documents Clear versioning type',
	docsClearVersioningComments: 'Documents Clear versioning comments',

	adminFoldersLoaded: 'Admin Folders loaded',
	adminFoldersSubFoldersLoaded: 'Admin Folders sub folders loaded',
	adminFoldersSaveHistory: 'Admin Folders save history',
	adminFoldersSaveCurrentFolders: 'Admin Folders save current folders',
	adminFoldersUpdateListHistory: 'Admin Folders update list history',
	adminFoldersOpenModal: 'Admin Folders open modal',
	adminFoldersCloseModal: 'Admin Folders close modal',
	adminFoldersSetActionModal: 'Admin Folders set action modal',
	adminFoldersRemoveActionModal: 'Admin Folder remove action modal',
	adminFoldersSetFolder: 'Admin Folders set folder',
	adminFoldersSaveLoaded: 'Admin Folders save loaded',
	adminFoldersUpdateLoaded: 'Admin Folders update loaded',
	adminFoldersRemoveAll: 'Admin Folders remove all',
	adminFoldersDeleteFolderLoaded: 'Admin Folders delete folder loaded',

}