export const types = {

	login: 'Auth Login',
	logout: 'Auth Logout',

	uiLoginShowLoader: 'UI Login show loading',
	uiLoginFinishLoader: 'UI Login finish loading',
	uiLoginShowMessageError: 'UI Login show message error',
	uiLoginRemoveMessageError: 'UI Login remove message error',

	foldersInitLoaded: 'Folders Init Loaded',
	foldersSetChildren: 'Folders Set children',
	foldersSaveIds: 'Folders Save ids',
	foldersRemoveId: 'Folders Remove id',
	foldersSaveAll: 'Folders Save all folders',
	foldersSelected: 'Folders Selected',
	foldersRemoveAll: 'Folders Remove All',
	pathFolderName:'Folders Name Path',
	clearFolderIdOrigin:'Folders Clear folderId',
	foldersValidateName: "Folders Validate Name",

	auditDataLoaded: 'Audit Data Loaded',
	auditRemoveAll: 'Audit Remove All',

	uiAuditShowLoader: 'UI Audit show loading',
	uiAuditFinishLoader: 'UI Audit finish loading',

	reportsDataLoaded: 'Reports Data Loaded',
	missingDataLoaded: 'Reports Missing Loaded',
	withoutDataLoaded:'Reports Without Loaded',
	reportsRemoveAll:'Reports Remove All',

	firmDataLoaded:'Firm Data Loaded',

	searchFieldsLoaded: 'Search Fields loaded',
	searchLoaded: 'Search Loaded',
	searchDocumentDeleted: 'Search Deleted document',
	searchSetText: 'Search Set Text',
	searchRemoveText: 'Search Remove Text',
	searchRemoveAll: 'Search Remove All',
	searchSetValueFilter: 'Search Set value filter',
	searchClearAllFilters: 'Search Clear all filters',
	changeCleanFilter: 'Change Clear Filter',
	searchSubscribeDocumentFinish: 'Search subscribe document finish',
	visibilityOpenModal: 'Visibility Open Modal',
	visibilityCloseModal: 'Visibility Close Modal',
	firmOpenModal: 'Firm Open Modal',
	firmCloseModal: 'Firm Close Modal',
	versioningOpenModal: 'Versioning Open Modal',
	versioningCloseModal: 'Versioning Close Modal',
	versioningLoaded:'Versioning Loaded',
	versioningRemove:'Versioning Remove',
	previewLoaded: "Preview Document Loaded",
	
	savedSearchesAddSearch: "Add new saved search", 
	savedSearchesList: "Saved searches All", 

	docsDocumentsTypeLoaded: 'Documents Type documents loaded',
	docsDetailDocumentTypeLoaded: 'Documents Detail document type loaded',
	docsRemoveAll: 'Documents Remove all',
	docsRemoveDetailDocumentType: 'Documents Remove detail document type',
	docsRemoveFile: 'Documents Remove document',
	docsSetValueField: 'Documents Set value field',
	docsSaveFormFinish: 'Documents Save form finish',
	docsSaveFolderId: 'Documents Save folder ID',
	docsSaveFileIdLoaded: 'Documents Save file ID loaded',
	docsSaveThumbnailGenerated: 'Documents Save thumbnailGenerated',
	docsSaveThumbnail: 'Documents Save thumbnail',
	docsClear: 'Documents Clear',
	docsCloseModalMultiSelect: 'Documents Close modal multi select',
	docsDocumentByIdLoaded: 'Documents Document by ID loaded',
	docsTagsLoaded: 'Documents Tags Loaded',
	docsSaveVersioningType: 'Documents Save versioning type',
	docsSaveVersioningComments: 'Documents Save versioning comments',
	docsClearVersioningType: 'Documents Clear versioning type',
	docsClearVersioningComments: 'Documents Clear versioning comments',
	docsFoldersLoaded: 'Documents Folders Loaded',
	docsSetSubFoldersToFolder: 'Documents Set Sub Folder to folder',
	docsSaveHistoryFoldersBreadcrumbs: 'Documents Save history folders Breadcrumbs',
	docsSaveCurrentFolderBreadcrumbs: 'Documents Save current folder Breadcrumbs',
	docsUpdateHistoryFoldersBreadcrumbs: 'Documents Update history folders Breadcrumbs',
	docsSaveFolderName: 'Documents Save folder name',
	docsAddAndRemoveTag: 'Documents Add and Remove tag',
	docsLoadingModalFolder: 'Documents Loading modal folder',
	docsDocumentByIdVisibility: 'Documents Visibility',
	clearDocsDocumentByIdVisibility: 'Clear DocsDocument visibility',
	docsDocumentsOfficeLoaded: 'Documents Office Loaded',


	adminFoldersLoaded: 'Admin Folders loaded',
	adminFoldersSubFoldersLoaded: 'Admin Folders sub folders loaded',
	adminFoldersSaveHistory: 'Admin Folders save history',
	adminFoldersSaveCurrentFolders: 'Admin Folders save current folders',
	adminFoldersUpdateListHistory: 'Admin Folders update list history',
	adminFoldersOpenModal: 'Admin Folders open modal',
	adminFoldersCloseModal: 'Admin Folders close modal',
	adminFoldersSetActionModal: 'Admin Folders set action modal',
	adminFoldersRemoveActionModal: 'Admin Folder remove action modal',
	adminFoldersSetFolder: 'Admin Folders set folder',
	adminFoldersSaveLoaded: 'Admin Folders save loaded',
	adminFoldersUpdateLoaded: 'Admin Folders update loaded',
	adminFoldersRemoveAll: 'Admin Folders remove all',
	adminFoldersDeleteFolderLoaded: 'Admin Folders delete folder loaded',
	adminfoldersTypesLoaded:'Admin Folders Types Loaded',
	adminfoldersTypesClear: 'Admin Folders Type Clear',
	adminFoldersUpdateCurrentFolders: 'Admin Folders Update Current Folders',
	
	tagsInitLoaded: 'Tags List',
	tagsAdd: 'Tags New',
	tagsEdit: 'Tags Edit',
	tagsDeleteLoaded: 'Tags delete loaded',
	tagsOpenModal: 'Tags Open Modal',
	tagsCloseModal: 'Tags Close Modal',
	tagsSetActionModal: 'Tags Action Modal',
	tagsSetFolder: 'Tags set folder',
	tagsSaveLoaded: 'Tags save loaded',
	tagsUpdateLoaded: 'Tags update loaded',
	tagsRemoveAll: 'Tags Remove all',

	attachmentsDataLoaded:'Attachments Data Loaded',
	commentsDataLoaded: 'Comments Data Loaded',
	informationRemoveAll: 'Information Remove All',

	addBreadcrumbs: 'Add BreadCrumbs',
	createBreadcrumbs: 'Create BreadCrumbs',

	usersOpenModal: 'Users Open Modal',
	usersCloseModal: 'Users Close Modal',
	usersInitLoaded: 'Users List',
	usersValidateNickname: 'Users Validate Nickname',
	usersSaveLoaded: 'Users Save Loaded',
	usersGroupSaveLoaded: 'Users Group Save Loaded',
	usersGroupOpenModal: 'Users Group Open Modal',
	usersGroupCloseModal: 'Users Group Close Modal',
	usersDeleteLoaded: 'Users Delete Loaded',
	usersAllInitLoaded: 'Users All Init Loaded',
	
	companyInitLoaded: 'Companies',
	departmentsInitLoaded: 'Departments',
	dependenciesInitLoaded: 'Dependencies',
	profilesInitLoaded: 'Profiles',
	membersInitLoaded: 'Members Group',
	groupValidateName: 'Group Validate Name',
	groupInitLoaded: 'Group List',
	groupOpenModal: 'Group Open Modal',
	groupCloseModal: 'Group Close Modal',
	groupSaveLoaded: 'Group Save Loaded',
	groupDeleteLoaded: 'Group Delete Loaded',


	sharedDocumentSetValue: 'shared Document Set Value',
	saveSharedFile: 'Save new shared file',
	saveFileStatus: "save file status data",
	sharedFileClearErrors: "Clear fields errors",
	sharedFileNotFoundError: "Not found file shared",
	sharedFileClearValues: "Clear all values file shared",

	restorePasswordSaveStatus: "Save status restore password",
	restorePasswordSuccess: "Restore password verificate success",
	addModulePermission: "Add new item in module permission",
	actionsModuleSetValueField: "set field value from form",
	actionsModuleClear: "Clear all values from action modules",

	approvesListLoaded: "Approves list loaded",
	flowsLoaded: "Flows Loaded",
	docsSaveFlowInit: "Docs Sabe Flow Init",
	taskResp: "Task Resp",

	tasksListLoaded: "Tasks List Loaded",
	flowListLoaded: "Flow List Loaded",
	involvedListLoaded: "Involved List Loaded",
	notificationsLoaded: "Notifications loaded",
	notificationsInitialLoad: "notifications Initial Load",
	notificationsChangeState: "Change notification state",
	notificationsReset: "Notifications reset initial values",

}